spring:
  application:
    name: randevu
  profiles:
    active: dev

firebase:
  credentials-path: classpath:firebase/firebase-service-account.json
  enabled: true

# iyzico ödeme entegrasyonu
iyzico:
  api-key: sandbox-5Wc829gg8VJjfHhJeCdw9Bwxc8l4ObfT
  secret-key: sandbox-JXN2QSOePp8jmrxw5XB3eq1GLffkMUMi
  base-url: https://sandbox-api.iyzipay.com
  callback-url: http://localhost:8080/api/v1/payments/callback
  deposit-rate: 0.20

app:
  notification:
    reminder-hours-before: 24
    review-request-hours-after: 1
  frontend-url: http://localhost:3000
